alias rni='react-native run-ios --simulator=“iPhone 11 Pro Max”'
alias ga='git add .'
alias gc='git commit -m'
alias gp='git push'
alias dev='git checkout dev && git pull'
alias comm='cd ~/desktop/simble/comm'
alias d='cd ~/desktop'
alias resi='cd ~/desktop/simble/ss-residential'
alias open-config='code ~/.bash_profile'
alias rni-device='react-native run-ios --device=“jpdi”'
alias gm='git merge --no-ff'
alias rni-release='react-native run-ios --configuration Release'
alias record='xcrun simctl io booted recordVideo demo.mp4'
alias reload-config='source ~/.bash_profile'
PS1='[\W]\$ '

export PATH=$PATH:/Users/jamesduong/bin